// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChatgptAuthTokensRefreshReason } from "./ChatgptAuthTokensRefreshReason.js";

export type ChatgptAuthTokensRefreshParams = { reason: ChatgptAuthTokensRefreshReason,
/**
 * Workspace/account identifier that Codex was previously using.
 *
 * Clients that manage multiple accounts/workspaces can use this as a hint
 * to refresh the token for the correct workspace.
 *
 * This may be `null` when the prior auth state did not include a workspace
 * identifier (`chatgpt_account_id`).
 */
previousAccountId?: string | null, };
