// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateLimitSnapshot } from "./RateLimitSnapshot.js";

export type GetAccountRateLimitsResponse = {
/**
 * Backward-compatible single-bucket view; mirrors the historical payload.
 */
rateLimits: RateLimitSnapshot,
/**
 * Multi-bucket view keyed by metered `limit_id` (for example, `codex`).
 */
rateLimitsByLimitId: { [key in string]?: RateLimitSnapshot } | null, };
