// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type McpResourceReadParams = { threadId?: string | null,
/**
 * Originating MCP tool call used to select the resource's app.
 */
originCallId?: string | null, server: string, uri: string, connectorId?: string | null, };
