// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRoot } from "./ProjectRoot.js";

export type ProjectImportParams = { name: string, roots: Array<ProjectRoot>, metadata?: { [key in string]?: string } | null, threads?: Array<string> | null, idempotencyKey: string, };
