// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Project } from "./Project.js";

export type ProjectListResponse = { data: Array<Project>, nextCursor: string | null, };
