// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - how an existing agent item appears in a realtime conversation.
 */
export type ThreadRealtimeBemItemPresentation = { "type": "wholeItem" } | { "type": "inlineMarkdown" } | { "type": "inlineVisualization", index: number, };
