// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - final transcript text emitted when realtime completes
 * a transcript part.
 */
export type ThreadRealtimeTranscriptDoneNotification = { threadId: string, role: string,
/**
 * Final complete text for the transcript part.
 */
text: string, };
