// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * EXPERIMENTAL - transport used by thread realtime.
 */
export type ThreadRealtimeStartTransport = { "type": "websocket" } | { "type": "webrtc",
/**
 * SDP offer generated by a WebRTC RTCPeerConnection after configuring audio and the
 * realtime events data channel.
 */
sdp: string, } | { "type": "existingCall",
/**
 * Identifier of a realtime call already created and negotiated by the client.
 */
callId: string, };
