// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for `thread/decrement_elicitation`.
 */
export type ThreadDecrementElicitationParams = {
/**
 * Thread whose out-of-band elicitation counter should be decremented.
 */
threadId: string, };
