// ADS-GENERATED FILE — DO NOT EDIT BY HAND.
// Regenerate via `npm run codex:regen-types` (requires `codex` CLI on PATH).
// Source: `codex app-server generate-ts`.
// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Internal Responses API passthrough metadata copied into underlying chat messages.
 *
 * Responses API strongly types this payload. Do not modify it without first getting API
 * approval and making the corresponding Responses API change.
 */
export type InternalChatMessageMetadataPassthrough = { turn_id?: string, };
