import { ref } from "vue";

import { createLiveActivityWindow } from "../lib/live_activity";
import type { ProjectRuntime } from "./controllerTypes";

export function createProjectRuntime(options: { maxLiveActivitySteps: number }): ProjectRuntime {
  return {
    projectSessionId: "",
    chatSessionId: "main",
    connected: ref(false),
    needsTaskResync: false,
    apiError: ref<string | null>(null),
    apiNotice: ref<string | null>(null),
    wsError: ref<string | null>(null),
    threadWarning: ref<string | null>(null),
    availableAgents: ref([]),
    activeAgentId: ref(""),
    activeThreadId: ref<string | null>(null),
    queueStatus: ref(null),
    workspacePath: ref(""),
    tasks: ref([]),
    selectedId: ref<string | null>(null),
    runBusyIds: ref(new Set()),
    busy: ref(false),
    turnInFlight: false,
    turnHasPatch: false,
    pendingAckClientMessageId: null,
    messages: ref([]),
    recentCommands: ref([]),
    turnCommands: [],
    turnCommandCount: 0,
    executePreviewByKey: new Map(),
    executeOrder: [],
    seenCommandIds: new Set(),
    pendingImages: ref([]),
    queuedPrompts: ref([]),
    delegationsInFlight: ref([]),
    ignoreNextHistory: false,
    ws: null,
    reconnectTimer: null,
    reconnectAttempts: 0,
    pendingCdRequestedPath: null,
    suppressNextClearHistoryResult: false,
    noticeTimer: null,
    liveActivity: createLiveActivityWindow(options.maxLiveActivitySteps),
    liveActivityTtlTimer: null,
    startedTaskIds: new Set(),
    taskChatBufferByTaskId: new Map(),
  };
}
